name: Commit Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: Format code
    uses: ./.github/workflows/format.yml
    permissions:
      contents: write
  
  test:
    name: Run tests
    needs: format
    uses: ./.github/workflows/test.yml
  
