name: CI Pipeline

on:
  push:
    branches: [ '**' ]
    branches-ignore:
      - 'release-v*'
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  format:
    name: Format code
    uses: ./.github/workflows/format.yml
    permissions:
      contents: write
  
  test:
    name: Run tests
    needs: format
    uses: ./.github/workflows/test.yml
  
  build:
    name: Build package
    needs: test
    uses: ./.github/workflows/build.yml
